harmony-chart:
  ingress-nginx:
    enabled: false
    controller:
      ingressClass: nginx

  cert-manager:
    enabled: false
    installCRDs: false
    # Email address associated with the ACME account. Used to notify about expiring
    # certificates.
    email: ""